"""Constants used for the expected headers of the database."""

PLAYER = 'Players'
GAME = 'Game'
STYLE = 'Playstyle'
IS_VICTOR = 'Won?'
TOTAL_LINES = 'Total Lines'
FINAL_SCORE = 'Final Score'
FIRST_19_LINES = '19 L Start'
SCORE_AT_19 = '19 Trans'
SCORE_IN_19 = 'Post Score'
FIRST_29_LINES = '29 L Start'
SCORE_AT_29 = '29 Trans'
LINES_IN_29 = '29 Lines'
SCORE_IN_29 = '29 Score'
NO_MULLEN_LINES = 'No M Lines'
NO_M_SCORE = 'No M Score'
TOPOUT_TYPE = 'Topout Type'
CAP_TYPE = 'Cap'
IS_SPS_MATCH = 'SPS'
START_LVL = 'Lvl Start'
EVENT = 'Event'
ROUND = 'Round'
GAME_LINK = 'Game Link'
MATCH_PAIRING = 'Match Pairing'
GAME_ID = 'Game ID'
MATCH_ID = 'Match ID'
YEAR = 'Year'
